In [26]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

In [28]:
mp_key = "71t7m37H7F5Jw2PfGOrlKxgH4ZbRQh3W"
mp_id = "mp-11739"

In [29]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [34]:
lattice = prim_struc.lattice
direct_vectors = lattice.matrix  # Matrice 3x3 contenant les vecteurs du réseau direct

print("Vecteurs de base du réseau direct :")
print(direct_vectors)

a, b, c = direct_vectors

# Calcul des longueurs des vecteurs
length_a = np.linalg.norm(a)
length_b = np.linalg.norm(b)
length_c = np.linalg.norm(c)

print(f"Longueur de a = {length_a} Angström")
print(f"Longueur de b = {length_b} Angström")
print(f"Longueur de c = {length_c} Angström")

Vecteurs de base du réseau direct :
[[ 8.29989832e+00 -2.35468939e+00 -9.25040000e-04]
 [ 8.29989832e+00  2.35468939e+00 -9.25040000e-04]
 [ 7.63231986e+00 -0.00000000e+00  4.02250914e+00]]
Longueur de a = 8.627448933573376 Angström
Longueur de b = 8.627448933573376 Angström
Longueur de c = 8.627449578336227 Angström


In [35]:
reciprocal_lattice = lattice.reciprocal_lattice
reciprocal_vectors = reciprocal_lattice.matrix  # Matrice 3x3 contenant les vecteurs réciproques

print("Vecteurs de base du réseau réciproque :")
print(reciprocal_vectors)

a, b, c = reciprocal_vectors

# Calcul des longueurs des vecteurs réciproques
length_a = np.linalg.norm(b1)
length_b = np.linalg.norm(b2)
length_c = np.linalg.norm(b3)

print(f"Longueur de a* = {length_a} Angström⁻¹")
print(f"Longueur de b* = {length_b} Angström⁻¹")
print(f"Longueur de c* = {length_c} Angström⁻¹")


Vecteurs de base du réseau réciproque :
[[ 3.78429750e-01 -1.33418559e+00 -7.18033644e-01]
 [ 3.78429750e-01  1.33418559e+00 -7.18033644e-01]
 [ 1.74051888e-04  0.00000000e+00  1.56167622e+00]]
Longueur de a* = 1.561676207785567 Angström⁻¹
Longueur de b* = 1.561676207785567 Angström⁻¹
Longueur de c* = 1.5616762343792705 Angström⁻¹


In [32]:
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
sga = SpacegroupAnalyzer(conv_struc)

crystal_system = sga.get_crystal_system()
lattice_type = sga.get_lattice_type()

print(f"Système cristallin : {crystal_system}")
print(f"Type de maille : {lattice_type}")

Système cristallin : trigonal
Type de maille : rhombohedral


In [33]:
point_group = sga.get_point_group_symbol()

print(f"Groupe ponctuel : {point_group}")

Groupe ponctuel : -3m
