In [3]:
import numpy as np
from pymatgen.core.structure import Structure
from pymatgen.ext.matproj import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core.operations import SymmOp
from jupyter_jsmol.pymatgen import quick_view

In [4]:
# Clé API et ID Matériau
mp_key = "71t7m37H7F5Jw2PfGOrlKxgH4ZbRQh3W"
mp_id = "mp-11739"

In [5]:
# Chargement de la structure depuis Materials Project
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
# Conversion en structure conventionnelle
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()

# Analyseur de groupe d'espace
sga = SpacegroupAnalyzer(conv_struc)
sym_ops = sga.get_symmetry_operations()

In [7]:
# Fonction pour afficher la structure
def show_structure(structure):
    view = quick_view(structure, "packed", conventional=True)
    display(view)
    return view

In [8]:
# Affichage de la structure de base
view=show_structure(conv_struc)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [13]:
i_atom = 1  # Atome K
i_symmop = 1  # Opération de symétrie : inversion

symmop = sym_ops[i_symmop]
pos_init = conv_struc.sites[i_atom - 1].frac_coords
pos_final = symmop.operate(pos_init)
matrix = symmop.rotation_matrix
tau = symmop.translation_vector

print(f"Position initiale de K : {pos_init}")
print(f"Matrice de transformation :\n{matrix}")
print(f"Vecteur tau : {tau}")
print(f"Position finale de K : {pos_final}")

Position initiale de K : [0.33333333 0.66666667 0.16666667]
Matrice de transformation :
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
Vecteur tau : [0. 0. 0.]
Position finale de K : [-0.33333333 -0.66666667 -0.16666667]


In [14]:
# Vérification manuelle du calcul
pos_computed = np.dot(matrix, pos_init) + tau
print(f"Position calculée manuellement : {pos_computed}")

Position calculée manuellement : [-0.33333333 -0.66666667 -0.16666667]


In [15]:
view1 = quick_view(conv_struc, "packed", conventional=True)
display(view1)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [16]:
view1.script('select K; color cyan')
view1.script('draw SYMOP 2 {atomno = 1}')

In [34]:
i_atom = 7  # Atome Te
i_symmop = 2  # Opération de symétrie : rotation

symmop = sym_ops[i_symmop]
pos_init = conv_struc.sites[i_atom - 1].frac_coords
pos_final = symmop.operate(pos_init)
matrix = symmop.rotation_matrix
tau = symmop.translation_vector

print(f"Position initiale de Te : {pos_init}")
print(f"Matrice de transformation :\n{matrix}")
print(f"Vecteur tau : {tau}")
print(f"Position finale de Te : {pos_final}")

Position initiale de Te : [0.         0.         0.26073622]
Matrice de transformation :
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
Vecteur tau : [0. 0. 0.]
Position finale de Te : [0.         0.         0.26073622]


In [27]:
# Vérification manuelle du calcul
pos_computed = np.dot(matrix, pos_init) + tau
print(f"Position calculée manuellement : {pos_computed}")

Position calculée manuellement : [0.         0.         0.26073622]


In [28]:
view2 = quick_view(conv_struc, "packed", conventional=True)
display(view2)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [29]:
view2.script('select Te; color blue')
view2.script('draw SYMOP 3 {atomno = 7}')

In [35]:
i_atom = 5  # Atome La
i_symmop = 7  # Opération de symétrie : roto-réflexion

symmop = sym_ops[i_symmop]
pos_init = conv_struc.sites[i_atom - 1].frac_coords
pos_final = symmop.operate(pos_init)
matrix = symmop.rotation_matrix
tau = symmop.translation_vector

print(f"Position initiale de La : {pos_init}")
print(f"Matrice de transformation :\n{matrix}")
print(f"Vecteur tau : {tau}")
print(f"Position finale de La : {pos_final}")

Position initiale de La : [0.66666667 0.33333333 0.33333333]
Matrice de transformation :
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
Vecteur tau : [0. 0. 0.]
Position finale de La : [-0.33333333 -0.66666667  0.33333333]


In [36]:
# Vérification manuelle du calcul
pos_computed = np.dot(matrix, pos_init) + tau
print(f"Position calculée manuellement : {pos_computed}")

Position calculée manuellement : [-0.33333333 -0.66666667  0.33333333]


In [37]:
view3 = quick_view(conv_struc, "packed", conventional=True)
display(view3)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [38]:
# Appliquer la roto-réflexion sur le Te (opération 8, atome 7)
view3.script('select La; color orange')  
view3.script('draw SYMOP 8 {atomno = 5}')

view3.script('draw PLANE xy')  # Dessine le plan de réflexion
view3.script('rotate z 180')   # Applique une rotation de 180° autour de Z
